export var DIRECTION;
(function (DIRECTION) {
	DIRECTION['ROW'] = 'row';
	DIRECTION['COLUMN'] = 'column';
})(DIRECTION || (DIRECTION = {}));
export var MARGIN_SIDES;
(function (MARGIN_SIDES) {
	MARGIN_SIDES['TOP'] = 'top';
	MARGIN_SIDES['RIGHT'] = 'right';
	MARGIN_SIDES['BOTTOM'] = 'bottom';
	MARGIN_SIDES['LEFT'] = 'left';
})(MARGIN_SIDES || (MARGIN_SIDES = {}));
export var ALIGN_ITEMS;
(function (ALIGN_ITEMS) {
	ALIGN_ITEMS['NORMAL'] = 'normal';
	ALIGN_ITEMS['FLEX_START'] = 'flex-start';
	ALIGN_ITEMS['FLEX_END'] = 'flex-end';
	ALIGN_ITEMS['CENTER'] = 'center';
	ALIGN_ITEMS['BASELINE'] = 'baseline';
	ALIGN_ITEMS['STRETCH'] = 'stretch';
	ALIGN_ITEMS['START'] = 'start';
	ALIGN_ITEMS['END'] = 'end';
	ALIGN_ITEMS['SELF_START'] = 'self-start';
	ALIGN_ITEMS['SELF_END'] = 'self-end';
	ALIGN_ITEMS['FIRST_BASELINE'] = 'first baseline';
	ALIGN_ITEMS['LAST_BASELINE'] = 'last baseline';
	ALIGN_ITEMS['SAFE_CENTER'] = 'safe center';
	ALIGN_ITEMS['UNSAFE_CENTER'] = 'unsafe center';
	ALIGN_ITEMS['SAFE_RIGHT'] = 'safe right';
	ALIGN_ITEMS['UNSAFE_RIGHT'] = 'unsafe right';
	ALIGN_ITEMS['SAFE_END'] = 'safe end';
	ALIGN_ITEMS['UNSAFE_END'] = 'unsafe end';
	ALIGN_ITEMS['SAFE_SELF_END'] = 'safe self-end';
	ALIGN_ITEMS['UNSAFE_SELF_END'] = 'unsafe self-end';
	ALIGN_ITEMS['SAFE_FLEX_END'] = 'safe flex-end';
	ALIGN_ITEMS['UNSAFE_FLEX_END'] = 'unsafe flex-end';
})(ALIGN_ITEMS || (ALIGN_ITEMS = {}));
export var JUSTIFY_CONTENT;
(function (JUSTIFY_CONTENT) {
	JUSTIFY_CONTENT['START'] = 'start';
	JUSTIFY_CONTENT['END'] = 'end';
	JUSTIFY_CONTENT['FLEX_START'] = 'flex-start';
	JUSTIFY_CONTENT['FLEX_END'] = 'flex-end';
	JUSTIFY_CONTENT['CENTER'] = 'center';
	JUSTIFY_CONTENT['LEFT'] = 'left';
	JUSTIFY_CONTENT['RIGHT'] = 'right';
	JUSTIFY_CONTENT['SPACE_BETWEEN'] = 'space-between';
	JUSTIFY_CONTENT['SPACE_AROUND'] = 'space-around';
	JUSTIFY_CONTENT['SPACE_EVENLY'] = 'space-evenly';
	JUSTIFY_CONTENT['STRETCH'] = 'stretch';
})(JUSTIFY_CONTENT || (JUSTIFY_CONTENT = {}));
export var SIZE_UNITS;
(function (SIZE_UNITS) {
	SIZE_UNITS['AUTO'] = 'auto';
	SIZE_UNITS['PERCENT'] = '%';
	SIZE_UNITS['FN'] = 'fn';
	SIZE_UNITS['PX'] = 'px';
	SIZE_UNITS['FR'] = 'fr';
	SIZE_UNITS['REM'] = 'rem';
	SIZE_UNITS['VH'] = 'vh';
	SIZE_UNITS['VW'] = 'vw';
	SIZE_UNITS['PC'] = 'pc';
	SIZE_UNITS['CM'] = 'cm';
	SIZE_UNITS['MM'] = 'mm';
	SIZE_UNITS['IN'] = 'in';
	SIZE_UNITS['PT'] = 'pt';
	SIZE_UNITS['CH'] = 'ch';
	SIZE_UNITS['EM'] = 'em';
	SIZE_UNITS['V_MIN'] = 'vmin';
	SIZE_UNITS['V_MAX'] = 'vmax';
})(SIZE_UNITS || (SIZE_UNITS = {}));
export var COLOR_MODE;
(function (COLOR_MODE) {
	COLOR_MODE['DARK'] = 'dark';
	COLOR_MODE['LIGHT'] = 'light';
})(COLOR_MODE || (COLOR_MODE = {}));
